name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  DOCKER_BUILDKIT: 1
  DOCKERHUB_USER: fthaler
  DOCKERHUB_REPOSITORY: fthaler/gridtools-base


jobs:
  base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: >
        docker build
        --progress=plain
        --cache-from $DOCKERHUB_REPOSITORY:base
        --tag $DOCKERHUB_REPOSITORY:base
        --build-arg REPOSITORY=$DOCKERHUB_REPOSITORY
        base
    - name: Push
      if: ${{ github.event_name == 'push' && github.repository == 'GridTools/gridtools-docker' }}
      run: >
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u $DOCKERHUB_USER --password-stdin &&
        docker push $DOCKERHUB_REPOSITORY &&
        docker logout

  gcc:
    runs-on: ubuntu-latest
    needs: base
    strategy:
      matrix:
        version: [8, 9, 10]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: >
        docker build
        --progress=plain
        --cache-from $DOCKERHUB_REPOSITORY:base
        --cache-from $DOCKERHUB_REPOSITORY:gcc-${{ matrix.version }}
        --tag $DOCKERHUB_REPOSITORY:gcc-${{ matrix.version }}
        --build-arg REPOSITORY=$DOCKERHUB_REPOSITORY
        --build-arg GCC_VERSION=${{ matrix.version }}
        gcc
    - name: Push
      if: ${{ github.event_name == 'push' && github.repository == 'GridTools/gridtools-docker' }}
      run: >
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u $DOCKERHUB_USER --password-stdin &&
        docker push $DOCKERHUB_REPOSITORY &&
        docker logout

  clang:
    runs-on: ubuntu-latest
    needs: base
    strategy:
      matrix:
        version: [9, 10, 11]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: >
        docker build
        --progress=plain
        --cache-from $DOCKERHUB_REPOSITORY:base
        --cache-from $DOCKERHUB_REPOSITORY:clang-${{ matrix.version }}
        --tag $DOCKERHUB_REPOSITORY:clang-${{ matrix.version }}
        --build-arg REPOSITORY=$DOCKERHUB_REPOSITORY
        --build-arg CLANG_VERSION=${{ matrix.version }}
        clang
    - name: Push
      if: ${{ github.event_name == 'push' && github.repository == 'GridTools/gridtools-docker' }}
      run: >
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u $DOCKERHUB_USER --password-stdin &&
        docker push $DOCKERHUB_REPOSITORY &&
        docker logout

  clang-cuda:
    runs-on: ubuntu-latest
    needs: base
    strategy:
      matrix:
        version: [11]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: >
        docker build
        --progress=plain
        --cache-from $DOCKERHUB_REPOSITORY:base
        --cache-from $DOCKERHUB_REPOSITORY:clang-${{ matrix.version }}
        --cache-from $DOCKERHUB_REPOSITORY:clang-${{ matrix.version }}-cuda-11
        --tag $DOCKERHUB_REPOSITORY:clang-${{ matrix.version }}-cuda-11
        --build-arg REPOSITORY=$DOCKERHUB_REPOSITORY
        --build-arg CLANG_VERSION=${{ matrix.version }}
        clang-cuda
    - name: Push
      if: ${{ github.event_name == 'push' && github.repository == 'GridTools/gridtools-docker' }}
      run: >
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u $DOCKERHUB_USER --password-stdin &&
        docker push $DOCKERHUB_REPOSITORY &&
        docker logout

  hip:
    runs-on: ubuntu-latest
    needs: base
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: >
        docker build
        --progress=plain
        --cache-from $DOCKERHUB_REPOSITORY:base
        --cache-from $DOCKERHUB_REPOSITORY:hip
        --tag $DOCKERHUB_REPOSITORY:hip
        --build-arg REPOSITORY=$DOCKERHUB_REPOSITORY
        hip
    - name: Push
      if: ${{ github.event_name == 'push' && github.repository == 'GridTools/gridtools-docker' }}
      run: >
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u $DOCKERHUB_USER --password-stdin &&
        docker push $DOCKERHUB_REPOSITORY &&
        docker logout

  hpx:
    runs-on: ubuntu-latest
    needs: gcc
    strategy:
      matrix:
        base: [gcc-10]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: >
        docker build
        --progress=plain
        --cache-from $DOCKERHUB_REPOSITORY:base
        --cache-from $DOCKERHUB_REPOSITORY:${{ matrix.base }}
        --cache-from $DOCKERHUB_REPOSITORY:${{ matrix.base }}-hpx
        --tag $DOCKERHUB_REPOSITORY:${{ matrix.base }}-hpx
        --build-arg REPOSITORY=$DOCKERHUB_REPOSITORY
        --build-arg BASE=${{ matrix.base }}
        hpx
    - name: Push
      if: ${{ github.event_name == 'push' && github.repository == 'GridTools/gridtools-docker' }}
      run: >
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u $DOCKERHUB_USER --password-stdin &&
        docker push $DOCKERHUB_REPOSITORY &&
        docker logout

  atlas:
    runs-on: ubuntu-latest
    needs: gcc
    strategy:
      matrix:
        base: [gcc-9]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: >
        docker build
        --progress=plain
        --cache-from $DOCKERHUB_REPOSITORY:base
        --cache-from $DOCKERHUB_REPOSITORY:${{ matrix.base }}
        --cache-from $DOCKERHUB_REPOSITORY:${{ matrix.base }}-atlas
        --tag $DOCKERHUB_REPOSITORY:${{ matrix.base }}-atlas
        --build-arg REPOSITORY=$DOCKERHUB_REPOSITORY
        --build-arg BASE=${{ matrix.base }}
        atlas
    - name: Push
      if: ${{ github.event_name == 'push' && github.repository == 'GridTools/gridtools-docker' }}
      run: >
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u $DOCKERHUB_USER --password-stdin &&
        docker push $DOCKERHUB_REPOSITORY &&
        docker logout
